### ISSUE TITLE
Make a button or quick way to fully expand/contract the symphony logic

### ISSUE THREAD

**Issue by markhicken** [Hickinvest/composer-quant-tools#8]
Something like this...
`document.querySelectorAll('.-rotate-90').forEach(el => el.click())`

**Comment by markhicken** [comment]
See the branch for this. It still needs a warning about expanding causing a bunch of additional fetches.
We may also want to make it work on all views, not just the edit view.

**Comment by jhicken** [comment]
I think this is done right? #13
